<a href="https://colab.research.google.com/github/Divyanshu592/Classwork_CDAC/blob/main/classwork.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1. Most expensive car for each car company make.

#2.Most expensive convertible vehicle for each company.

#3.List all the cars which are automatic.

#4. Premium cars of each car company

# 5. Average price of cars each car company make.

In [1]:
import pandas as pd
import numpy as np

In [80]:
df=pd.read_csv("car.csv")

## Most expensive car for each car company make.

In [81]:
df1=df.groupby("Make")["MSRP"].max()
print(df1)

Make
Acura             156000
Alfa Romeo         68400
Aston Martin      320695
Audi              199900
BMW               141200
Bentley           363000
Bugatti          2065902
Buick              49625
Cadillac          104215
Chevrolet          92395
Chrysler           49470
Dodge             120395
FIAT               31800
Ferrari           643330
Ford              149995
GMC                71665
Genesis            54550
HUMMER             43130
Honda              47070
Hyundai            68750
Infiniti           88850
Kia                61900
Lamborghini      1500000
Land Rover        199495
Lexus             375000
Lincoln            76650
Lotus              93225
Maserati          182009
Maybach          1382750
Mazda              44015
McLaren           280225
Mercedes-Benz     495000
Mitsubishi         38995
Nissan            149990
Oldsmobile         36795
Plymouth           44625
Pontiac            37610
Porsche           440000
Rolls-Royce       492425
Saab               51330
Scion              31090
Spyker            219990
Subaru             39995
Suzuki             31749
Tesla             134500
Toyota             84325
Volkswagen        101300
Volvo              65700
Name: MSRP, dtype: int64

## Most expensive convertible vehicle for each company

In [89]:
df2 = df[df["Vehicle Style"] == "Convertible"].groupby("Make")["MSRP"].max()
print(df2)

Make
Alfa Romeo         65900
Aston Martin      320695
Audi              199600
BMW               136900
Bentley           363000
Buick              37065
Cadillac          104215
Chevrolet          92395
Chrysler           49470
Dodge               2000
FIAT               28195
Ferrari           294080
Ford               60110
Honda              37995
Infiniti           62100
Lamborghini       548800
Lexus              68405
Lotus              57950
Maserati          182009
Maybach          1382750
Mazda              32655
McLaren           280225
Mercedes-Benz     495000
Mitsubishi         32599
Nissan             49400
Oldsmobile          2000
Plymouth           44625
Pontiac            32300
Porsche           440000
Rolls-Royce       492000
Saab               51330
Spyker            219990
Toyota             30710
Volkswagen         42745
Volvo              41200
Name: MSRP, dtype: int64

## List all the cars which are automatic.

In [85]:
df3 = df[df["Transmission Type"] == "AUTOMATIC"]
display(df3)

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
19,Audi,100,1992,regular unleaded,172.0,6.0,AUTOMATIC,all wheel drive,4.0,Luxury,Midsize,Wagon,20,16,3105,2000
23,Audi,100,1993,regular unleaded,172.0,6.0,AUTOMATIC,all wheel drive,4.0,Luxury,Midsize,Wagon,20,16,3105,2000
27,Audi,100,1994,regular unleaded,172.0,6.0,AUTOMATIC,front wheel drive,4.0,Luxury,Midsize,Wagon,21,16,3105,2000
30,Audi,100,1994,regular unleaded,172.0,6.0,AUTOMATIC,front wheel drive,4.0,Luxury,Midsize,Sedan,22,16,3105,2000
31,Audi,100,1994,regular unleaded,172.0,6.0,AUTOMATIC,all wheel drive,4.0,Luxury,Midsize,Wagon,21,16,3105,2000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11909,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,46120
11910,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,56670
11911,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50620
11912,Acura,ZDX,2013,premium unleaded (recommended),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50920
11913,Lincoln,Zephyr,2006,regular unleaded,221.0,6.0,AUTOMATIC,front wheel drive,4.0,Luxury,Midsize,Sedan,26,17,61,28995

# Premium cars of each car company

In [88]:
df4 = df[df["Engine Fuel Type"].str.contains("premium", na=False)]
df4

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11908,Acura,ZDX,2011,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50520
11909,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,46120
11910,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,56670
11911,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50620
11912,Acura,ZDX,2013,premium unleaded (recommended),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50920

# Average price of cars each car company make.

In [87]:
df5 = df.groupby("Make")["MSRP"].mean().astype(int)
df5

Make
Acura              34887
Alfa Romeo         61600
Aston Martin      197910
Audi               53452
BMW                61546
Bentley           247169
Bugatti          1757223
Buick              28206
Cadillac           56231
Chevrolet          28350
Chrysler           26722
Dodge              22390
FIAT               22670
Ferrari           238218
Ford               27399
GMC                30493
Genesis            46616
HUMMER             36464
Honda              26674
Hyundai            24597
Infiniti           42394
Kia                25310
Lamborghini       331567
Land Rover         67823
Lexus              47549
Lincoln            42839
Lotus              69188
Maserati          114207
Maybach           546221
Mazda              20039
McLaren           239805
Mercedes-Benz      71476
Mitsubishi         21240
Nissan             28583
Oldsmobile         11542
Plymouth            3122
Pontiac            19321
Porsche           101622
Rolls-Royce       351130
Saab               27413
Scion              19932
Spyker            213323
Subaru             24827
Suzuki             17907
Tesla              85255
Toyota             29030
Volkswagen         28102
Volvo              28541
Name: MSRP, dtype: int64